### ISSUE TITLE
Streamlit app down

### ISSUE THREAD

**Issue by ICWallis** [Geothermal-Resource-Capacity/Power-Density#13]
Not sure why yet, but the streamlit app is not working :-(  Error message on the streamlit app page is "Whoops — something went wrong! An error has been logged."

**Comment by Japhiolite** [comment]
Here's the log from building the app
[logs-geothermal-resource-capacity-power-density-main-streamlit-Power-Density_streamlit.py-2022-04-03T10 55 20.314Z.txt](https://github.com/Geothermal-Resource-Capacity/Power-Density/files/8404319/logs-geothermal-resource-capacity-power-density-main-streamlit-Power-Density_streamlit.py-2022-04-03T10.55.20.314Z.txt)

**Comment by Japhiolite** [comment]
App is running again. We had the versions frozen in the old requirements.txt, so a streamlit version was installed, which didn't yet have the `columns` method.
I _unfroze_ the requirements and removed the old one.
Just for the archive (so we don't need to dig through commits in a future, when we'd potentially need the old requirements), these were the old requirements:
```
altair==4.1.0
matplotlib==3.3.4
matplotlib-inline==0.1.2
numpy==1.20.1
pandas==1.2.4
pip==21.0.1
plotly==4.14.3
scipy==1.6.2
streamlit==0.82.0
```
